### ISSUE TITLE
tests fail in windows

### ISSUE THREAD

**Issue by JEBailey** [xvxx/vial#13]
Two tests fail when running in a windows environment.
The first is util > file_size. It appears that git will change the line endings of certain files automatically between unix and windows. So instead of finding 1052 and 25161 for the files in the test, it finds 1072 and 25835 respectively.

Additionally, the file_walker test fails. This is actually a problem with the PathBuf object which allows you to construct a path that ends up being a mix of UNIX and Windows-based file path separators.  So rather than "tests/assets/rfcs/rfc1288.txt" you get
"tests/assets/rfcs\\rfc1288.txt" as the comparison.

**Comment by xvxx** [comment]
Thank you! I merged PR #14 but there will still be other issues, for example the "asset bundling" feature relies on symlinks and assumes a UNIX environment.
