### ISSUE TITLE
Replace serde with nanoserde?

### ISSUE THREAD

**Issue by alexwennerberg** [xvxx/vial#16]
How would you feel about replacing serde with the lighter-weight https://github.com/not-fl3/nanoserde for json serialization?

**Comment by alexwennerberg** [comment]
I may put together a PR then! I really like vial and I use it for https://finger.flounder.online/ -- I'm thinking of using it for a more substantial project I have planned too

Another project I wanted to put on your radar is nanotemplate:

https://git.sr.ht/~jpastuszek/nanotemplate

I'm using it as a templating engine in one of my projects as an alternative to horrorshow

**Comment by Zireael07** [comment]
@alexwennerberg: Got the PR? Interested in seeing such a replacement in practice...

**Comment by alexwennerberg** [comment]
@Zireael07 for nanoserde? sadly no, I've been caught up with my day job

**Comment by xvxx** [comment]
Added nanoserde support in 766c5af9c40b9de61edc5ff3499135bc95469a44, while also keeping Serde available if people want it.
